### PR TITLE
Galician translation

### PR DESCRIPTION
**Pull request by qosobrin**

### CODE REVIEW

**Comment by persianpros** [comment]
There's no Galician support in enigma2 AFAIK so we need es_GL like pt_BR first.

**Comment by qosobrin** [comment]
> There's no Galician support in enigma2 AFAIK so we need es_GL like pt_BR first.

What is the procedure to provide Galician (gl) support to engima2? I'd like to lead that project but I have found no information on how to start it.

Thank you very much.
Regards.

**Comment by persianpros** [comment]
You could provide the new language po based on https://github.com/OpenPLi/enigma2/blob/develop/po/es.po I think right?

After having a new language file the support could be added by us (developers) to enigma2 itself, so no hard things for you to do.

Although different images have different strings but the main strings are the same so later you could provide those.

**Comment by qosobrin** [comment]
OK, I'm working on it; it's a big file so it's going to take me a while. I started last week and I'm 25% done right now but I'm going to slow down during December. 

In a separate matter but somehow related to this one, I noticed that the Spanish translation is very poor (many wrongly translated strings). I wonder if any change done to this file (https://github.com/OpenPLi/enigma2/blob/develop/po/es.po) will be committed upstream to enigma2 itself and downstream to the other images based on it or I should commit those changes in a different place. 

Thank you very much.
Regards.

**Comment by qosobrin** [comment]
Hi, @persianpros 

I have just started https://github.com/OpenPLi/enigma2/pull/2826 but merging is blocked. I hope you can review my work, if necessary, and merge it.

Also, as I also say in the Pull Request, I hope you will publish the promised guide on how to create and maintain a language in enigma2, specially for those like me that want to work upstream for the translations to move downstream to the different images.

Thank you very much.

**Pull request closed without merging**
